"""
Derin Öğrenme Kütüphanelerinin Kurulumu

Öncelikle CMD açıyoruz.
github üzerinden theano kütüphanesini kurmamız gerekiyor.
Kurulum için:
- pip install --upgrade --no-deps  git+git://github.com/Theanor/Theano.git
daha sonra tensorflow kurulumu için

- pip3 install --upgrade tensorflow
- pip3 install --upgrade tensorflow-gpu

Keras'ı indirmek için de aynı terminali kullanacağız.
- pip install -upgrade keras


Bunun için alt + ctrl + s yapıp kütüphane indirme bölümünden kütüphaneyi indirebilirsin.

---GİT CLONE da unutma
"""
